name: Apply terraform for the github runner

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-docker:
    name: Build and deploy
  
    steps:
      - uses: actions/checkout@v2

      - name: Docker test
        run: |
         docker build -t testjan .
         docker run -v /:/test testjan
         docker images
         docker ps
